Repository KikyoNanakusa/websystem-django-mock, pull requests merged in 2025-01, with the labels that each got.

#19 商品の詳細ページを作成した。
  app/BookReview/templates/index.html
  app/BookReview/templates/product_detail.html
  app/BookReview/urls.py
  app/BookReview/views.py
Labels: Tier1

#41 getting started を追加
  docs/README.md
Labels: documentation

#42 docker composeを修正
  .gitignore
  docker-compose.yaml
Labels: bug

#51 全体的にデザインを改善
  .gitignore
  app/BookReview/templates/about.html
  app/BookReview/templates/base.html
  app/BookReview/templates/category_products.html
  app/BookReview/templates/contact.html
  app/BookReview/templates/index.html
  app/BookReview/templates/login.html
  app/BookReview/templates/product_detail.html
  app/BookReview/templates/signup.html
  app/static/style/category_products.css
  app/static/style/contact.css
  app/static/style/global.css
  app/static/style/index.css
  app/static/style/login.css
  app/static/style/product_detail.css
  app/static/style/signup.css
Labels: Tier2
